name: CI - Build Backend

on:
  pull_request:
    branches:
      - main
    paths:
      - backend/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./backend
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:15.4
        # Provide the password for postgres
        env:
          POSTGRES_USER: shreeya
          POSTGRES_PASSWORD: password
          POSTGRES_DATABASE: customer
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build and run Unit/Integration tests with Maven
        run: mvn -ntp -B verify